### ISSUE TITLE
Dependent repos are still private

### ISSUE THREAD

**Issue by jc00ke** [engineyard/eycloud-app-jenkins#2]
```
gem install engineyard-recipes
ey-recipes init --on-deploy --sm
ey-recipes sm git@github.com:engineyard/sm_eyapi.git -n eyapi
ey-recipes sm git@github.com:engineyard/sm_jenkins.git install configure restart -n jenkins
```

from the README, yet both `sm_eyapi` & `sm_jenkins` are private, therefore the last 2 commands fail

```
∴ ey-recipes sm git@github.com:engineyard/sm_eyapi.git -n eyapi
       exist  deploy/cookbooks
   identical  deploy/cookbooks/eyapi/attributes/recipe.rb
   identical  deploy/cookbooks/eyapi/recipes/default.rb
   identical  deploy/cookbooks/eyapi/recipes/install_sm_ext.rb
      append  deploy/cookbooks/main/recipes/default.rb
ERROR: Repository not found.
fatal: The remote end hung up unexpectedly
```

**Comment by drnic** [comment]
Bah. Does this mean the whole app failed to work? I thought the app still should work without any dependency repos.

**Comment by jc00ke** [comment]
I got through the first 2 commands, and that was it. It's not clear by the `README` that I would _not_ need to do those two `ey-recipes sm` commands.

**Comment by drnic** [comment]
You should be able to ignore the README. It is just me documenting how I created this wrapper app from other chef/SM recipes.

Take the git URI and launch it on EY Cloud. It should "just work". 

If not, let me know.

**Comment by drnic** [comment]
Added "how to use this thing" instructions to readme
